

# artist_discovery:
#     popularity_threshold: 50

#     seed_artists: [
#         'AP Dhillon', 'Raf Saperra', 'Rovalio'
#     ]

#     include_genres: ["bhojpuri pop"]

#     exclude_genres: ['art pop', 'chicago rap', 'norwegian pop', 'folk-pop']

artist_discovery:
    popularity_threshold: 50

    seed_artists: [
        'AP Dhillon', 'Raf Saperra', 'Rovalio', 'Divine', 
        'Prateek Kuhad', 'Lisa Mishra','Rahul', 'Abdullah Siddiqui', 'Ikky', 
        'Shubh', 'Karan Aujla', 'Hassan Raheem', 'AUR', 'King', 'Sharn', 
        'Ranj', 'Clifr', 'Umair', 'Abhi The Nomad', 'MC Stan','Young Stunners',
        'Prabh Singh', 'Prabh Deep', 'Lifafa', 'Badshah', 'Taimoor Baig', 'Umair'
    ]

    include_genres: [
    "bhojpuri pop",
    "carnatic vocal",
    "chutney",
    "classic bangla pop",
    "classic bhangra",
    "classic bollywood",
    "classic pakistani pop",
    "classic punjabi pop",
    "desi hip hop",
    "desi pop",
    "desi trap",
    "filmi",
    "garhwali pop",
    "ghazal",
    "goa hip hop",
    "gujarati garba",
    "gujarati pop",
    "haryanvi hip hop",
    "himachali pop",
    "hindi hip hop",
    "hindi indie",
    "hindustani classical",
    "hindustani instrumental",
    "hindustani vocal",
    "indian ambient",
    "indian classical",
    "indian edm",
    "indian electronic",
    "indian folk",
    "indian fusion",
    "indian indie",
    "indian instrumental",
    "indian instrumental rock",
    "indian lo-fi",
    "indian percussion",
    "indian rock",
    "indian singer-songwriter",
    "indian underground rap",
    "indiana indie",
    "indie pop rap",
    "kannada hip hop",
    "kannada pop",
    "kashmiri hip hop",
    "kashmiri pop",
    "kolkata indie",
    "kollywood",
    "malayalam hip hop",
    "malayalam indie",
    "malayalam pop",
    "malaysian hip hop",
    "malaysian tamil pop",
    "malaysian tamil rap",
    "marathi hip hop",
    "marathi pop",
    "marathi traditional",
    "modern bollywood",
    "mollywood",
    "mumbai indie",
    "nagaland indie",
    "new delhi indie",
    "northeast indian hip hop",
    "northeast indian indie",
    "pakistani folk",
    "pakistani hip hop",
    "pakistani indie",
    "pakistani pop",
    "pakistani rock",
    "political hip hop",
    "pune indie",
    "punjabi folk",
    "punjabi hip hop",
    "punjabi pop",
    "qawwali",
    "rajasthani pop",
    "sindhi",
    "sufi",
    "tabla",
    "tamil hip hop",
    "tamil indie",
    "tamil pop",
    "telugu hip hop",
    "tollywood",
    "uk desi rap",
    "uk hip hop",
    "urdu hip hop",
    "vintage tollywood",
    "west bengali pop",
    "afghan pop",
    "arunachal indie",
    "assamese pop",
    "balochi pop",
    "bangalore indie",
    "bangla pop",
    "bangladeshi hip hop",
    "bhangra",
    "bhojpuri folk",
    "bhojpuri pop",
    "carnatic",
    "chennai indie",
    "chill dream pop",
    "chutney",
    "classic bangla pop",
    "classic bhangra",
    "classic bollywood",
    "classic kollywood",
    "classic konkani pop",
    "classic pakistani pop",
    "classic punjabi pop",
    "deathgrass",
    "desi emo rap",
    "desi hip hop",
    "desi pop",
    "desi trap",
    "filmi",
    "gujarati garba",
    "gujarati pop",
    "haryanvi hip hop",
    "hindi hip hop",
    "hindi indie",
    "indian classical",
    "indian edm",
    "indian electronic",
    "indian folk",
    "indian fusion",
    "indian indie",
    "indian rock",
    "indian singer-songwriter",
    "kannada hip hop",
    "manipuri pop",
    "marathi pop",
    "modern bollywood",
    "new delhi indie",
    "northeast indian indie",
    "pakistani electronic",
    "pakistani hip hop",
    "pakistani indie",
    "pakistani pop",
    "punjabi folk",
    "punjabi hip hop",
    "punjabi lo-fi",
    "punjabi pop",
    "uk desi rap",
    "urdu hip hop"]

    exclude_genres: ['art pop', 'chicago rap', 'norwegian pop', 'folk-pop']